### ISSUE TITLE
value_shape

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/libtab#24]
Some elements may need a value shape as well as a value size

**Comment by chrisrichardson** [comment]
Regge already falls into this category.
In ffcx it is not too problematic, as we get the size/shape from ufl. But it is probably a good idea to add this...
I suggest we change `int value_size` to `vector<int> value_shape` and add a convenience function `value_size()` that returns `product(value_shape)`.

**Comment by chrisrichardson** [comment]
Completed with PR #27
