### ISSUE TITLE
Interface to quadrature rules

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/libtab#31]
FFCx wants to use quadrature rules from libtab (https://github.com/FEniCS/ffcx/blob/3c7727c75afcb4882214f1678d005eb92e2eb737/ffcx/libtab_interface.py#L15), but currently I think they are only available externally for simplices

**Comment by chrisrichardson** [comment]
This should be fairly simple to implement, at least for tensor product type elements. Probably easiest to replace the `create_quadrature(dim, order)` with `create_quadrature(celltype, order)`...

**Comment by mscroggs** [comment]
`create_quadrature(celltype, order)` would make the implementation in FFCx very simple

**Comment by jhale** [comment]
There are use cases for the new DOLFINX Expression code where it would definitely be nice to have the quadrature points at runtime: https://github.com/FEniCS/dolfinx/blob/master/python/test/unit/function/test_expression_evaluation.py#L203

**Comment by chrisrichardson** [comment]
@jhale - I think there will be quite a few instances where we need the same information in ffcx and at runtime, so it will be a case of using `libtab` in ffcx to create tables etc., and linking against the same library in `dolfinx` - we will need to take care with versioning.

**Comment by chrisrichardson** [comment]
Fixed with PR #33
